Add email updating volunteers on things and mentoring
srobo/volunteer-emails pull request #40
Opened 2021-01-21 23:03 UTC by RealOrangeOne

Add email updating volunteers on how things are going, and asking for mentors for teams.

Related to https://github.com/srobo/team-emails/pull/74/

2021-01-21 23:18 UTC, PeterJCLaw approved these changes

2021-01-22 09:06 UTC, rgilton commented on SR2021/2021-01-23-mentors.md
> +awesome. As ever, if you’d like to get involved please join us in our [Slack][slack]
Conflicts with the sign-up directions for both teams, as discussed in email.

2021-01-22 09:07 UTC, rgilton requested changes
Sign-up instructions are incorrect.

2021-01-22 09:34 UTC, RealOrangeOne commented on SR2021/2021-01-23-mentors.md
> +awesome. As ever, if you’d like to get involved please join us in our [Slack][slack]
Mabe this should read strictly towards contributing to SR2021, rather than SR as a whole? At which point I think this wording is correct.

```suggestion
awesome. As ever, if you’d like to get involved in helping bring SR2021 to life, please join us in our [Slack][slack]
```

2021-01-27 08:51 UTC, merged