Add a draft of the volunteer competition information pack
srobo/volunteer-emails pull request #54
Opened 2022-04-09 19:07 UTC by Scarzy

2022-04-09 20:16 UTC, Tyler-Ward requested changes
See inline comment

2022-04-09 20:16 UTC, Tyler-Ward commented on SR2022/2022-04-09-competition-information-pack.md
> +Hot drinks, cold drinks, and snacks will be available throughout the competition and the setup days. If possible, please bring a re-usable mug to make your drinks in so we can limit waste. You will n
This is probably insufficient information to prevent volunteers arriving without lunch due to facilities being closed, suggest the following wording replace the last sentence and to have it as a separate paragraph.

This year we will not be providing lunch, in addition the food venues that are close to the venue have either closed or are not open during the competition so you will need to bring lunch with you. For those not familiar with southampton there is a Sainsburys on burgess road about 10 minutes walk away and another in ports wood a short drive away. On Sunday due to the marathon access to those may be difficult and the one in portswood will not be open before the event starts. 

@Adimote are there any food venues between the airbnbs we organised and the venue we should mention

2022-04-10 08:34 UTC, antoinepetty commented on SR2022/2022-04-09-competition-information-pack.md
> +Hot drinks, cold drinks, and snacks will be available throughout the competition and the setup days. If possible, please bring a re-usable mug to make your drinks in so we can limit waste. You will n
Isn't this covered more concisely in this line? https://github.com/srobo/volunteer-emails/pull/54/files#diff-a0ed561c16f83cca0537f891b657d4cfc830fd08599a0e0c992432f60fa77374R37

2022-04-10 10:13 UTC, Scarzy commented on SR2022/2022-04-09-competition-information-pack.md
> +Hot drinks, cold drinks, and snacks will be available throughout the competition and the setup days. If possible, please bring a re-usable mug to make your drinks in so we can limit waste. You will n
There is a lot of points this e-mail needs to cover, and frankly the fact people will have to provide their own lunches is fairly low down that list. Everything needs to be stated succinctly to ensure that everything is read.

There is a list of food venues on the main competition event page (which is already linked to in this e-mail), also our volunteers are quite adept at using Google, so they have multiple means of locating a food vendor. The extra limitations imposed by the marathon only apply to 1 of the 5 days and as Antoine says that is covered more concisely in the marathon section. We also cannot state that the nearby food vendors are closed because of the marathon, simply because we don't know that they are. Equally, we don't know what additional food vendors may be available because of the marathon.
Anyone attending on the Thursday, Friday, or Saturday will be aware that they need to have brought their own and on those days will have more opportunity to get something last minute, and we can remind people in briefings on Saturday to have some pre-planned for the Sunday. So as I see it the risk is only really 1-2 people forgetting on the Sunday, and then there are various means for them to get food anyway, be that them walking to a vendor, someone going to a vendor for them, or them getting something delivered.

As such I'm quite keen to keep this point as brief as possible to ensure people don't skim past either it, or the various other more important points. As it the statement is quite clear about what SR will provide, what volunteers will need to provide, and is accurate for all days of the competition.

2022-04-10 14:19 UTC, RealOrangeOne commented on SR2022/2022-04-09-competition-information-pack.md
> +## Venue opening times
We should clarify that this is for the Saturday / Sunday. Competitors won't be there on Thursday / Friday. Are the opening times still the same on the setup days?

2022-04-10 14:19 UTC, RealOrangeOne commented on SR2022/2022-04-09-competition-information-pack.md
> +Unfortunately we are unable to cover expenses for getting to the competition this year.
```suggestion
Unfortunately we are unable to cover expenses for getting to the competition or for accommodation this year.
```

2022-04-10 14:19 UTC, RealOrangeOne commented on SR2022/2022-04-09-competition-information-pack.md
> +Further information on many of these points can be found on the [competition event page](https://studentrobotics.org/events/sr2022/competition/), so keep an eye on this for updates. We welcome questi
```suggestion
Further information on many of these points can be found on the [competition event page](https://studentrobotics.org/events/sr2022/competition/), so keep an eye on this for updates. We welcome questions, so please feel free to ask (either by replying to this email or in Slack) if you need clarification on anything!
```

2022-04-10 14:19 UTC, RealOrangeOne commented on SR2022/2022-04-09-competition-information-pack.md
> +Hot drinks, cold drinks, and snacks will be available throughout the competition and the setup days. If possible, please bring a re-usable mug to make your drinks in so we can limit waste. You will n
We cover this a little bit below in the marathon section, as that's the main limiting factor. Personally I think what's here is fine, although I do think we should expand a little more to _recommend_ that people bring their lunch on both days (and perhaps setup?) to limit a sudden drop in volunteer numbers.

2022-04-10 16:02 UTC, WillB97 commented
General thoughts:
- We should say that setup is from Thursday and we are meeting at the entrance of SUSU at 9am
- There was talk that setup would need masks. If this is the case you need to say that or people won't bring masks

2022-04-10 20:26 UTC, Tyler-Ward commented on SR2022/2022-04-09-competition-information-pack.md
> +Hot drinks, cold drinks, and snacks will be available throughout the competition and the setup days. If possible, please bring a re-usable mug to make your drinks in so we can limit waste. You will n
per discussions on slack about plan Bs for those who forget (Note: given the wording above I would not bring a packed lunch due to expecting to be able to buy one) Here is a less verbose option that makes it more clear that pre action is needed.

We will not be providing lunches this year and food vendors close to the event will be closed you will need to bring your own packed lunch or make other plans.

2022-04-10 22:44 UTC, Scarzy commented on SR2022/2022-04-09-competition-information-pack.md
> +Hot drinks, cold drinks, and snacks will be available throughout the competition and the setup days. If possible, please bring a re-usable mug to make your drinks in so we can limit waste. You will n
> We will not be providing lunches this year and food vendors close to the event will be closed you will need to bring your own packed lunch or make other plans.

Again, we don't actually know that any vendors will be closed (at least beyond their normal Sunday opening hours).

> I do think we should expand a little more to recommend that people bring their lunch on both days (and perhaps setup?) to limit a sudden drop in volunteer numbers.

This isn't a bad shout.

I've done some rewording, hopefully this addresses both points

2022-04-10 22:44 UTC, Scarzy commented on SR2022/2022-04-09-competition-information-pack.md
> +## Venue opening times
Done, and added a separate bit on setup days

2022-04-10 22:45 UTC, Scarzy commented
> * We should say that setup is from Thursday and we are meeting at the entrance of SUSU at 9am
> * There was talk that setup would need masks. If this is the case you need to say that or people won't bring masks

Done and done

2022-04-10 23:39 UTC, Tyler-Ward commented on SR2022/2022-04-09-competition-information-pack.md
> +Hot drinks, cold drinks, and snacks will be available throughout the competition and the setup days. If possible, please bring a re-usable mug to make your drinks in so we can limit waste. You will n
Re food vendors being shut. The two closest that are the usual locations we would go for food are not open anymore/have misleading published opening times .
SUSU shop claim to be open on Sundays on google, they will not be open as they have different hours over Easter.
COOP on burgess road has closed permanently. (this was a surprise to most people in the competition team when this was mentioned so I expect will be to other volunteers as well)
The next closest is Sainsburys which is a 10-15min walk away.

2022-04-11 18:37 UTC, Scarzy commented on SR2022/2022-04-09-competition-information-pack.md
> +Hot drinks, cold drinks, and snacks will be available throughout the competition and the setup days. If possible, please bring a re-usable mug to make your drinks in so we can limit waste. You will n
SUSU shop claim to only be open Mon-Wed on their own website. As I can't find a marker for the shop itself on google maps I'm not really sure what you're basing that on?
Having skimmed down Burgess road on Google Maps and cross checked against vendors own websites, there seem to be multiple options within easy walking distance that will be available. I'm sure someone had a map of nearby vendors (though I personally can't currently find it). It feels like the best solution to this is to update that map and ensure it is available on the day.

However that is well beyond the scope of this PR. Unless there is a problem with the current wording(?) I'm going to resolve this conversation

2022-04-12 19:51 UTC, Adimote commented
Please send this ASAP, it should not block on the volunteer schedule. We'll send a separate email with volunteer roles

2022-04-12 19:54 UTC, Adimote commented on SR2022/2022-04-09-competition-information-pack.md
> +Please check the [volunteer schedule]() to see what roles you've been allocated. Role descriptions can be found [here](). Please read the descriptions for the roles you've been allocated to ensure yo
```suggestion
We're in the process of assigning volunteers, we'll soon be sending you an email with your individual roles and how to perform them, keep an eye out for it!
```

2022-04-12 19:55 UTC, antoinepetty commented on SR2022/2022-04-09-competition-information-pack.md
> +Please check the [volunteer schedule]() to see what roles you've been allocated. Role descriptions can be found [here](). Please read the descriptions for the roles you've been allocated to ensure yo
Yeah this is probably a good idea

2022-04-12 20:30 UTC, RealOrangeOne commented on SR2022/2022-04-09-competition-information-pack.md
> +You will have to complete a [Media Consent form](https://studentrobotics.org/resources/sr2022/media-consent.pdf). If you are able to complete this ahead of time that will be appreciated. There will b
```suggestion
You will have to complete a [Media Consent form](https://studentrobotics.org/resources/sr2022/media-consent.pdf). If you are able to complete this ahead of time and bring it with you, that will be appreciated. There will be a few spare media consent forms available.
```

2022-04-12 20:30 UTC, RealOrangeOne commented on SR2022/2022-04-09-competition-information-pack.md
> +On the Thursday and Friday, the venue doors will open at 09:00. We will be meeting in the SUSU entrance at this time. If you are arriving later in the day, then you will most likely find someone in t
> you will most likely find someone in the Cube

We should probably tell people where the cube is

```suggestion
On the Thursday and Friday, the venue doors will open at 09:00. We will be meeting in the SUSU entrance at this time. If you are arriving later in the day, then you will most likely find someone in the Cube (bottom of the stairs, turn left).
```

2022-04-12 20:30 UTC, RealOrangeOne commented on SR2022/2022-04-09-competition-information-pack.md
> +Further information on many of these points can be found on the [competition event page](https://studentrobotics.org/events/sr2022/competition/), so keep an eye on this for updates. We welcome questi
```suggestion
Further information on many of these points can be found on the [competition event page](https://studentrobotics.org/events/sr2022/competition/), so keep an eye on this for updates. We welcome questions, so please feel free to ask (either by replying to this email or in Slack ([sign up](https://goo.gl/forms/Maq41MHF8CYSRVn83))) if you need clarification on anything!
```

2022-04-12 20:50 UTC, RealOrangeOne commented on SR2022/2022-04-09-competition-information-pack.md
> +---
I can't do suggestions for filenames, but the date should probably be `2022-04-12`

2022-04-12 20:50 UTC, RealOrangeOne approved these changes

2022-04-12 21:02 UTC, Adimote approved these changes

2022-04-12 21:07 UTC, RealOrangeOne commented
Sent

2022-04-12 21:07 UTC, merged