SR2024 kick off email
srobo/volunteer-emails pull request #66
Opened 2023-07-12 22:28 UTC by sedders123

Still needs spellchecking, de-memeifying, and some links adding but this is what came out of the doing this evening

2023-09-27 19:27 UTC, Adimote approved these changes

2023-09-27 19:27 UTC, Adimote commented on SR2024/2023-07-15-sr2024-kickofff.md
> +- We'll soon be packing the kits for shipping which will require a lot of hands (no technical knowledge required!)
```suggestion
```
Delete this because it's now in the past

2023-09-27 19:28 UTC, Adimote requested changes
unapproving because I only approved accidentally

2023-09-27 19:49 UTC, PeterJCLaw commented on SR2024/2023-07-15-sr2024-kickofff.md
> +Infrastructure| Hit servers | infrastructure-committee@studentrobotics.org| Wednesday 7pm (monthly)
```suggestion
Infrastructure| Hit servers | infrastructure-committee@studentrobotics.org| Monday 7:30pm (monthly)
```

2023-09-27 19:50 UTC, PeterJCLaw commented on SR2024/2023-07-15-sr2024-kickofff.md
> +Volunteer Onboarding| Welcome wagon | onboarding@studentrobotics.org | TBC
```suggestion
Volunteer Onboarding| Welcome wagon | onboarding@studentrobotics.org | Tuesday 8pm (fortnightly)
```

2023-09-27 19:50 UTC, PeterJCLaw commented on SR2024/2023-07-15-sr2024-kickofff.md
> +Fundraising| Moollah | trustees@studentrobotics.org| Mondays 8:30pm
```suggestion
Fundraising| Moollah | trustees@studentrobotics.org| Monday 8:30pm

```

2023-09-27 19:51 UTC, Adimote commented on SR2024/2023-07-15-sr2024-kickofff.md
> +If you want to keep up to date with the latest happenings in Student Robotics then you can join our Slack. Most planning and ad-hoc communication occurs there and you'll be able to get stuck in if yo
```suggestion
If you want to keep up to date with the latest happenings in Student Robotics then you can [join our Slack](https://forms.gle/DsM45qByLA3heZELA). Most planning and ad-hoc communication occurs there and you'll be able to get stuck in if you want to!

```

2023-09-27 19:52 UTC, PeterJCLaw commented on SR2024/2023-07-15-sr2024-kickofff.md
> +You could also subscribe to SR(A)WN, our (almost) Weekly Newsletter. This contains headline updates from each Team and can be subscribed to via RSS or Google Groups.
```suggestion
You could also subscribe to [SR(A)WN](https://studentrobotics.org/srawn/), our (almost) Weekly Newsletter. This contains headline updates from each Team and can be subscribed to via [RSS](https://studentrobotics.org/srawn/rss.xml) or [Google Groups](https://groups.google.com/g/srawn).

```

2023-09-27 20:01 UTC, PeterJCLaw commented on SR2024/2023-07-15-sr2024-kickofff.md
> +- The physical competition needs a small army of volunteers to run in numerous technical and non technical roles. We'll open sign ups for volunteering at the event as soon as we can confirm the venue
```suggestion
- The physical competition needs a small army of volunteers to run in numerous technical and non technical roles. We'll open sign ups for volunteering at the event as soon as we can confirm the venue later in the year

```

2023-10-11 19:35 UTC, PeterJCLaw commented on SR2024/2023-07-15-sr2024-kickofff.md
> +Planning for SR2024 is underway! We're still in the early stages so this is the perfect time for you to get more involved.
```suggestion
Planning for SR2024 is underway! With Kickstart just around the corner now is a great time to get involved.
```

2023-11-22 22:02 UTC, antoinepetty commented
Looks good to me, but Onboarding meet weekly :) (or at least try to)

2023-11-22 22:04 UTC, PeterJCLaw commented
> Looks good to me, but Onboarding meet weekly :) (or at least try to)

a0a4e70

2023-11-22 22:04 UTC, antoinepetty commented
Also fundraising have fundraising@studentrobotics.org
I'd be tempted to put them above onboarding as they're more desperate for volunteers

2023-11-22 22:06 UTC, PeterJCLaw commented
> Also fundraising have [fundraising@studentrobotics.org](mailto:fundraising@studentrobotics.org)

I suspect the goal here was to include the email address of the relevant committees rather than the teams.

2023-11-23 08:57 UTC, antoinepetty commented
> I suspect the goal here was to include the email address of the relevant committees rather than the teams.

Ah we might want volunteer-onboarding-committee@studentrobotics.org for onboarding then? I don't mind onboarding@ though, much easier to type!

2023-11-23 09:05 UTC, PeterJCLaw commented
> > I suspect the goal here was to include the email address of the relevant committees rather than the teams.
> 
> Ah we might want [volunteer-onboarding-committee@studentrobotics.org](mailto:volunteer-onboarding-committee@studentrobotics.org) for onboarding then? I don't mind onboarding@ though, much easier to type!

I had a look at that, however volunteer-onboarding-committee@ doesn't seem to allow posts from external people?

2023-11-23 09:10 UTC, antoinepetty commented
> I had a look at that, however volunteer-onboarding-committee@ doesn't seem to allow posts from external people?

Ah I don't think that's intentional, I've just modified the team address to allow external emails but don't have access to modify the committee settings. Happy to keep it as onboarding@ here though

2023-11-29 21:11 UTC, Adimote approved these changes

2023-11-29 21:50 UTC, merged